version: "3.8"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: omnihr_user
      POSTGRES_PASSWORD: omnihr_pwd
      POSTGRES_DB: omnihr_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    command: ./docker-entrypoint.sh
    working_dir: /usr/src/app
    environment:
      DATABASE_HOST: db
      DJANGO_SETTINGS_MODULE: omnihr.local_settings
      DATABASE_USER: omnihr_user
      DATABASE_PASSWORD: omnihr_pwd
      DATABASE_NAME: omnihr_db
    depends_on:
      - "db"
    volumes:
      - ".:/usr/src/app"
